/**
 * Seed data for 50 World Cup players across different countries
 * Rarity taxonomy changed to: Common, Uncommon, Rare, Very Rare
 * ID blocks per team (each starts at a new hundred):
 * Argentina: 1000, Brazil: 1100, France: 1200, England: 1300,
 * Germany: 1400, Spain: 1500, Italy: 1600, Portugal: 1700,
 * Netherlands: 1800, Belgium: 1900
 *
 * Mapping used when converting old rarities:
 * Legendary -> Very Rare
 * Epic -> Rare
 * Rare -> Uncommon
 * Common -> Common
 */
export const seedPlayers = [
    // Argentina (6 players) - start 1000
    { id: 1000, playerName: "Emiliano Martínez", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 89 },
    { id: 1001, playerName: "Gerónimo Rulli", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 1002, playerName: "Valentín Barco", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Defender", overallRating: 75 },
    { id: 1003, playerName: "Nicolás Otamendi", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Defender", overallRating: 81 },
    { id: 1004, playerName: "Lisandro Martínez", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 86 },
    { id: 1005, playerName: "Nahuel Molina", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 1006, playerName: "Gonzalo Montiel", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Defender", overallRating: 80 },
    { id: 1007, playerName: "Cristian Romero", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 87 },
    { id: 1008, playerName: "Nicolás Tagliafico", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 1009, playerName: "Thiago Almada", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 84 },
    { id: 1010, playerName: "Enzo Fernández", teamName: "Argentina", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 1011, playerName: "Rodrigo De Paul", teamName: "Argentina", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 1012, playerName: "Alexis Mac Allister", teamName: "Argentina", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 87 },
    { id: 1013, playerName: "Giovani Lo Celso", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 1014, playerName: "Leandro Paredes", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 82 },
    { id: 1015, playerName: "Nico Paz", teamName: "Argentina", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 77 },
    { id: 1016, playerName: "Julián Álvarez", teamName: "Argentina", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 1017, playerName: "Nicolás González", teamName: "Argentina", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 84 },
    { id: 1018, playerName: "Lionel Messi", teamName: "Argentina", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 93 },
    { id: 1019, playerName: "Lautaro Martínez", teamName: "Argentina", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    // Brazil (6 players) - start 1100
    { id: 1100, playerName: "Alisson Becker", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 1101, playerName: "Ederson", teamName: "Brazil", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 1102, playerName: "Paulo Henrique", teamName: "Brazil", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 1103, playerName: "Danilo Pereira", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 1104, playerName: "Alex Sandro", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 1105, playerName: "Fabricio Bruno", teamName: "Brazil", rarityLevel: "Common", playerPosition: "Defender", overallRating: 79 },
    { id: 1106, playerName: "Gabriel Magalhães", teamName: "Brazil", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 1107, playerName: "Marquinhos", teamName: "Brazil", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 87 },
    { id: 1108, playerName: "Casemiro", teamName: "Brazil", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 1109, playerName: "Bruno Guimarães", teamName: "Brazil", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 87 },
    { id: 1110, playerName: "Fabinho", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 84 },
    { id: 1111, playerName: "Andrey Santos", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 1112, playerName: "Lucas Paquetá", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 85 },
    { id: 1113, playerName: "Estevão Willian", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 1114, playerName: "João Pedro", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 1115, playerName: "Matheus Cunha", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 1116, playerName: "Rodrygo", teamName: "Brazil", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    { id: 1117, playerName: "Richarlison", teamName: "Brazil", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 1118, playerName: "Vinícius Júnior", teamName: "Brazil", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 90 },
    { id: 1119, playerName: "Endrick", teamName: "Brazil", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 78 },
    // Italy (20 players) - start 2000
    { id: 2000, playerName: "Gianluigi Donnarumma", teamName: "Italy", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 2001, playerName: "Guglielmo Vicario", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 2002, playerName: "Marco Carnesecchi", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 2003, playerName: "Alessandro Bastoni", teamName: "Italy", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 2004, playerName: "Riccardo Calafiori", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2005, playerName: "Andrea Cambiaso", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 80 },
    { id: 2006, playerName: "Federico Dimarco", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2007, playerName: "Matteo Gabbia", teamName: "Italy", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 2008, playerName: "Gianluca Mancini", teamName: "Italy", rarityLevel: "Common", playerPosition: "Defender", overallRating: 79 },
    { id: 2009, playerName: "Leonardo Spinazzola", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2010, playerName: "Nicolo Barella", teamName: "Italy", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 87 },
    { id: 2011, playerName: "Davide Frattesi", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2012, playerName: "Manuel Locatelli", teamName: "Italy", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2013, playerName: "Samuele Ricci", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 2014, playerName: "Sandro Tonali", teamName: "Italy", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 87 },
    { id: 2015, playerName: "Riccardo Orsolini", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2016, playerName: "Giacomo Raspadori", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 84 },
    { id: 2017, playerName: "Francesco Pio Esposito", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 2018, playerName: "Mateo Retegui", teamName: "Italy", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 2019, playerName: "Moise Kean", teamName: "Italy", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    // Canada (20 players) - start 2100
    { id: 2100, playerName: "Milan Borjan", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 84 },
    { id: 2101, playerName: "Maxime Crépeau", teamName: "Canada", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 80 },
    { id: 2102, playerName: "Alistair Johnston", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2103, playerName: "Doneil Henry", teamName: "Canada", rarityLevel: "Common", playerPosition: "Defender", overallRating: 79 },
    { id: 2104, playerName: "Kamal Miller", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2105, playerName: "Cyle Larin", teamName: "Canada", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2106, playerName: "Stephen Eustáquio", teamName: "Canada", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2107, playerName: "Jonathan Osorio", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2108, playerName: "Atiba Hutchinson", teamName: "Canada", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2109, playerName: "Tajon Buchanan", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 84 },
    { id: 2110, playerName: "Alphonso Davies", teamName: "Canada", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 90 },
    { id: 2111, playerName: "Jonathan David", teamName: "Canada", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    { id: 2112, playerName: "Lucas Cavallini", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 2113, playerName: "Mark-Anthony Kaye", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2114, playerName: "Richie Laryea", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2115, playerName: "Kamal Miller", teamName: "Canada", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2116, playerName: "Cyle Larin", teamName: "Canada", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 2117, playerName: "Dejan Jakovic", teamName: "Canada", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 2118, playerName: "Alphonso Davies", teamName: "Canada", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 90 },
    { id: 2119, playerName: "Jonathan David", teamName: "Canada", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    // Switzerland (20 players) - start 2200
    { id: 2200, playerName: "Yann Sommer", teamName: "Switzerland", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 87 },
    { id: 2201, playerName: "Gregor Kobel", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 2202, playerName: "Kevin Mbabu", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2203, playerName: "Silvan Widmer", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2204, playerName: "Manuel Akanji", teamName: "Switzerland", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2205, playerName: "Ricardo Rodríguez", teamName: "Switzerland", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 2206, playerName: "Nico Elvedi", teamName: "Switzerland", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2207, playerName: "Fabian Frei", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2208, playerName: "Granit Xhaka", teamName: "Switzerland", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 87 },
    { id: 2209, playerName: "Djibril Sow", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2210, playerName: "Remo Freuler", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2211, playerName: "Xherdan Shaqiri", teamName: "Switzerland", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 2212, playerName: "Breel Embolo", teamName: "Switzerland", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 2213, playerName: "Haris Seferovic", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 2214, playerName: "Renato Steffen", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2215, playerName: "Seydou Doumbia", teamName: "Switzerland", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 78 },
    { id: 2216, playerName: "Silvan Hefti", teamName: "Switzerland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2217, playerName: "Cedric Itten", teamName: "Switzerland", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 79 },
    { id: 2218, playerName: "Remo Meyer", teamName: "Switzerland", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2219, playerName: "Loris Benito", teamName: "Switzerland", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    // Qatar
    { id: 2300, playerName: "Saad Al-Sheeb", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 2301, playerName: "Meshaal Barsham", teamName: "Qatar", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 78 },
    { id: 2302, playerName: "Boualem Khoukhi", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2303, playerName: "Pedro Miguel", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2304, playerName: "Tarek Salman", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 80 },
    { id: 2305, playerName: "Bassam Al-Rawi", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2306, playerName: "Ali Afif", teamName: "Qatar", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2307, playerName: "Abdulkarim Hassan", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2308, playerName: "Hassan Al-Haydos", teamName: "Qatar", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2309, playerName: "Akram Afif", teamName: "Qatar", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 2310, playerName: "Almoez Ali", teamName: "Qatar", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 87 },
    { id: 2311, playerName: "Mostafa Meshaal", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2312, playerName: "Mohammed Muntari", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 2313, playerName: "Pedro Miguel", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2314, playerName: "Ahmed Alaaeldin", teamName: "Qatar", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2315, playerName: "Khalid Muftah", teamName: "Qatar", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 2316, playerName: "Abdulrahman Al-Yami", teamName: "Qatar", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2317, playerName: "Mohammed Waad", teamName: "Qatar", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 2318, playerName: "Ali Samer", teamName: "Qatar", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 77 },
    { id: 2319, playerName: "Hassan Al-Haydos", teamName: "Qatar", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    // Mexico
    { id: 2400, playerName: "Guillermo Ochoa", teamName: "Mexico", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 2401, playerName: "Rodrigo Reyna", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 2402, playerName: "Johan Vásquez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2403, playerName: "Héctor Moreno", teamName: "Mexico", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2404, playerName: "Néstor Araujo", teamName: "Mexico", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 2405, playerName: "Luis Rodríguez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2406, playerName: "Carlos Salcedo", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 2407, playerName: "Edson Álvarez", teamName: "Mexico", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2408, playerName: "Hirving Lozano", teamName: "Mexico", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    { id: 2409, playerName: "Diego Lainez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 2410, playerName: "Raúl Jiménez", teamName: "Mexico", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 90 },
    { id: 2411, playerName: "Andrés Guardado", teamName: "Mexico", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2412, playerName: "Jorge Sánchez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2413, playerName: "Guido Rodríguez", teamName: "Mexico", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2414, playerName: "Erick Gutiérrez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2415, playerName: "Santiago Giménez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 2416, playerName: "Henry Martín", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2417, playerName: "Luis Romo", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2418, playerName: "José Juan Macías", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2419, playerName: "Erick Sánchez", teamName: "Mexico", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    // Poland
    { id: 2500, playerName: "Wojciech Szczęsny", teamName: "Poland", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 2501, playerName: "Łukasz Fabiański", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 2502, playerName: "Kamil Glik", teamName: "Poland", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2503, playerName: "Bartosz Bereszyński", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2504, playerName: "Jan Bednarek", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 2505, playerName: "Pawel Dawidowicz", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2506, playerName: "Tomasz Kędziora", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2507, playerName: "Grzegorz Krychowiak", teamName: "Poland", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2508, playerName: "Piotr Zieliński", teamName: "Poland", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 89 },
    { id: 2509, playerName: "Mateusz Klich", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 2510, playerName: "Jakub Moder", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2511, playerName: "Kamil Jóźwiak", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2512, playerName: "Robert Lewandowski", teamName: "Poland", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 92 },
    { id: 2513, playerName: "Karol Świderski", teamName: "Poland", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 2514, playerName: "Arkadiusz Milik", teamName: "Poland", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 2515, playerName: "Przemysław Frankowski", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 2516, playerName: "Kacper Kozłowski", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2517, playerName: "Mateusz Wieteska", teamName: "Poland", rarityLevel: "Common", playerPosition: "Defender", overallRating: 79 },
    { id: 2518, playerName: "Bartosz Slisz", teamName: "Poland", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2519, playerName: "Sebastian Szymański", teamName: "Poland", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    // Saudi Arabia
    { id: 2600, playerName: "Abdullah Al-Mayouf", teamName: "Saudi Arabia", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 87 },
    { id: 2601, playerName: "Mohammed Al-Owais", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 2602, playerName: "Ali Al-Bulaihi", teamName: "Saudi Arabia", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2603, playerName: "Abdullah Madu", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2604, playerName: "Mohammed Al-Fatil", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2605, playerName: "Yasser Al-Shahrani", teamName: "Saudi Arabia", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 84 },
    { id: 2606, playerName: "Mohammed Kanno", teamName: "Saudi Arabia", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2607, playerName: "Salem Al-Dawsari", teamName: "Saudi Arabia", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 2608, playerName: "Abdulrahman Ghareeb", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2609, playerName: "Mohammed Al-Breik", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2610, playerName: "Firas Al-Buraikan", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 83 },
    { id: 2611, playerName: "Saleh Al-Shehri", teamName: "Saudi Arabia", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 2612, playerName: "Mohammed Al-Sahlawi", teamName: "Saudi Arabia", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 84 },
    { id: 2613, playerName: "Nawaf Al-Abed", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 2614, playerName: "Hattan Bahebri", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2615, playerName: "Mohammed Al-Khabrani", teamName: "Saudi Arabia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 80 },
    { id: 2616, playerName: "Mohammed Al-Otaibi", teamName: "Saudi Arabia", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 79 },
    { id: 2617, playerName: "Abdullah Al-Khaibari", teamName: "Saudi Arabia", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2618, playerName: "Yahya Al-Shehri", teamName: "Saudi Arabia", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 78 },
    { id: 2619, playerName: "Abdullah Al-Khaibari", teamName: "Saudi Arabia", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    // Costa Rica
    { id: 2700, playerName: "Keylor Navas", teamName: "Costa Rica", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 2701, playerName: "Esteban Alvarado", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 2702, playerName: "Francisco Calvo", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2703, playerName: "Óscar Duarte", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2704, playerName: "Brenes González", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2705, playerName: "Bryan Oviedo", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2706, playerName: "Joel Campbell", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 2707, playerName: "Celso Borges", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2708, playerName: "Yeltsin Tejeda", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2709, playerName: "Christian Bolaños", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 2710, playerName: "Keysher Fuller", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2711, playerName: "Johan Venegas", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2712, playerName: "Bryan Ruiz", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2713, playerName: "Rodney Wallace", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2714, playerName: "Daniel Colindres", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 2715, playerName: "Óscar Ramírez", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2716, playerName: "David Guzmán", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2717, playerName: "Bryan Ruiz", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 2718, playerName: "Johnny Woodly", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 77 },
    { id: 2719, playerName: "Kendall Waston", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    // Costa Rica
    { id: 2700, playerName: "Keylor Navas", teamName: "Costa Rica", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 2701, playerName: "Esteban Alvarado", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 2702, playerName: "Francisco Calvo", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2703, playerName: "Óscar Duarte", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2704, playerName: "Brenes González", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2705, playerName: "Bryan Oviedo", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2706, playerName: "Joel Campbell", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 2707, playerName: "Celso Borges", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2708, playerName: "Yeltsin Tejeda", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2709, playerName: "Christian Bolaños", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 2710, playerName: "Keysher Fuller", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2711, playerName: "Johan Venegas", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2712, playerName: "Bryan Ruiz", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2713, playerName: "Rodney Wallace", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2714, playerName: "Daniel Colindres", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 2715, playerName: "Óscar Ramírez", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2716, playerName: "David Guzmán", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2717, playerName: "Bryan Ruiz", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 2718, playerName: "Johnny Woodly", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 77 },
    { id: 2719, playerName: "Kendall Waston", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    // Tunisia
    { id: 2900, playerName: "Aymen Mathlouthi", teamName: "Tunisia", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 87 },
    { id: 2901, playerName: "Montassar Talbi", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 81 },
    { id: 2902, playerName: "Mohamed Dräger", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2903, playerName: "Yassine Meriah", teamName: "Tunisia", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2904, playerName: "Ali Abdi", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 2905, playerName: "Aïssa Laïdouni", teamName: "Tunisia", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 2906, playerName: "Ellyes Skhiri", teamName: "Tunisia", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 2907, playerName: "Ferjani Sassi", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2908, playerName: "Mohamed Ali Ben Romdhane", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 2909, playerName: "Wahbi Khazri", teamName: "Tunisia", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 2910, playerName: "Seifeddine Jaziri", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2911, playerName: "Youssef Msakni", teamName: "Tunisia", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 2912, playerName: "Taha Yassine Khenissi", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 2913, playerName: "Ramy Bensebaini", teamName: "Tunisia", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 2914, playerName: "Mohamed Dräger", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 2915, playerName: "Yassine Chikhaoui", teamName: "Tunisia", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 2916, playerName: "Aymen Barkok", teamName: "Tunisia", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 2917, playerName: "Wahbi Khazri", teamName: "Tunisia", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 2918, playerName: "Anice Badri", teamName: "Tunisia", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 78 },
    { id: 2919, playerName: "Bassem Srarfi", teamName: "Tunisia", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    // Japan
    { id: 3000, playerName: "Eiji Kawashima", teamName: "Japan", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 87 },
    { id: 3001, playerName: "Daniel Schmidt", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 3002, playerName: "Maya Yoshida", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3003, playerName: "Takehiro Tomiyasu", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3004, playerName: "Hiroki Sakai", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 3005, playerName: "Shogo Taniguchi", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 3006, playerName: "Takefusa Kubo", teamName: "Japan", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3007, playerName: "Ao Tanaka", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3008, playerName: "Wataru Endo", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 3009, playerName: "Gaku Shibasaki", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 3010, playerName: "Ritsu Doan", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3011, playerName: "Takumi Minamino", teamName: "Japan", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    { id: 3012, playerName: "Ao Tanaka", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3013, playerName: "Yuya Osako", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 3014, playerName: "Kyogo Furuhashi", teamName: "Japan", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 3015, playerName: "Hidemasa Morita", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3016, playerName: "Daichi Kamada", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 3017, playerName: "Ritsu Doan", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3018, playerName: "Yuto Nagatomo", teamName: "Japan", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 3019, playerName: "Takehiro Tomiyasu", teamName: "Japan", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    // Ghana
    { id: 3100, playerName: "Richard Ofori", teamName: "Ghana", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 87 },
    { id: 3101, playerName: "Daniel Kofi Agyei", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 81 },
    { id: 3102, playerName: "Daniel Amartey", teamName: "Ghana", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3103, playerName: "Alexander Djiku", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 3104, playerName: "Mohammed Salisu", teamName: "Ghana", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3105, playerName: "Daniel Opare", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 3106, playerName: "Thomas Partey", teamName: "Ghana", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3107, playerName: "Mohammed Kudus", teamName: "Ghana", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 89 },
    { id: 3108, playerName: "Joseph Paintsil", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3109, playerName: "Ibrahim Sadiq", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 3110, playerName: "Jordan Ayew", teamName: "Ghana", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 3111, playerName: "Andre Ayew", teamName: "Ghana", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3112, playerName: "Kamaldeen Sulemana", teamName: "Ghana", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 3113, playerName: "Mohammed Abu", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 3114, playerName: "Iñaki Williams", teamName: "Ghana", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 3115, playerName: "Thomas Agyepong", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3116, playerName: "Salifu Ibrahim", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3117, playerName: "Joseph Aidoo", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 3118, playerName: "Alexander Djiku", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 3119, playerName: "Ibrahim Sadiq", teamName: "Ghana", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    // Spain
    { id: 3200, playerName: "Unai Simón", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 3201, playerName: "Robert Sánchez", teamName: "Spain", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 3202, playerName: "Jordi Alba", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3203, playerName: "Aymeric Laporte", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Defender", overallRating: 88 },
    { id: 3204, playerName: "Eric García", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3205, playerName: "Pau Torres", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3206, playerName: "José Gayà", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3207, playerName: "Sergio Busquets", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3208, playerName: "Pedri", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 89 },
    { id: 3209, playerName: "Gavi", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3210, playerName: "César Azpilicueta", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3211, playerName: "Ansu Fati", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    { id: 3212, playerName: "Álvaro Morata", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 87 },
    { id: 3213, playerName: "Ferrán Torres", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3214, playerName: "Dani Olmo", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 87 },
    { id: 3215, playerName: "Mikel Oyarzabal", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3216, playerName: "Rodri", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3217, playerName: "Thiago Alcântara", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3218, playerName: "Carlos Soler", teamName: "Spain", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 3219, playerName: "Aymeric Laporte", teamName: "Spain", rarityLevel: "Very Rare", playerPosition: "Defender", overallRating: 88 },
    // Costa Rica
    { id: 3300, playerName: "Esteban Alvarado", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 82 },
    { id: 3301, playerName: "Keylor Navas", teamName: "Costa Rica", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    { id: 3302, playerName: "Bryan Oviedo", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 3303, playerName: "Brenes González", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 3304, playerName: "Francisco Calvo", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3305, playerName: "Keysher Fuller", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 81 },
    { id: 3306, playerName: "Óscar Duarte", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 3307, playerName: "Celso Borges", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 3308, playerName: "Christian Bolaños", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 81 },
    { id: 3309, playerName: "David Guzmán", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 3310, playerName: "Johan Venegas", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 3311, playerName: "Johnny Woodly", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 77 },
    { id: 3312, playerName: "Daniel Colindres", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 81 },
    { id: 3313, playerName: "Joel Campbell", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3314, playerName: "Bryan Ruiz", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 3315, playerName: "Rodney Wallace", teamName: "Costa Rica", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3316, playerName: "Óscar Ramírez", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 3317, playerName: "Kendall Waston", teamName: "Costa Rica", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 3318, playerName: "Bryan Ruiz", teamName: "Costa Rica", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 3319, playerName: "Keylor Navas", teamName: "Costa Rica", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 88 },
    // Germany
    { id: 3400, playerName: "Kevin Trapp", teamName: "Germany", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 3401, playerName: "Marc-André ter Stegen", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Goalkeeper", overallRating: 89 },
    { id: 3402, playerName: "Antonio Rüdiger", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Defender", overallRating: 88 },
    { id: 3403, playerName: "Matthias Ginter", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3404, playerName: "Robin Gosens", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3405, playerName: "David Raum", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 86 },
    { id: 3406, playerName: "Niklas Süle", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3407, playerName: "Joshua Kimmich", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 89 },
    { id: 3408, playerName: "Leon Goretzka", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3409, playerName: "Ilkay Gündogan", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3410, playerName: "Julian Brandt", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 3411, playerName: "Kai Havertz", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    { id: 3412, playerName: "Karim Adeyemi", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 86 },
    { id: 3413, playerName: "Serge Gnabry", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 3414, playerName: "Leroy Sané", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 89 },
    { id: 3415, playerName: "Timo Werner", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Attacker", overallRating: 88 },
    { id: 3416, playerName: "Jamal Musiala", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 87 },
    { id: 3417, playerName: "Florian Wirtz", teamName: "Germany", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 3418, playerName: "Lukas Klostermann", teamName: "Germany", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 3419, playerName: "Kai Havertz", teamName: "Germany", rarityLevel: "Very Rare", playerPosition: "Midfielder", overallRating: 88 },
    // Ecuador
    { id: 3700, playerName: "Moisés Ramírez", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 3701, playerName: "Hernán Galíndez", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 79 },
    { id: 3702, playerName: "Pervis Estupiñán", teamName: "Ecuador", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3703, playerName: "Piero Hincapié", teamName: "Ecuador", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3704, playerName: "Willian Pacho", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 84 },
    { id: 3705, playerName: "Félix Torres", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 3706, playerName: "Ángelo Preciado", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 82 },
    { id: 3707, playerName: "Piero Hincapié", teamName: "Ecuador", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3708, playerName: "Xavier Arreaga", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Defender", overallRating: 79 },
    { id: 3709, playerName: "José Hurtado", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Defender", overallRating: 78 },
    { id: 3710, playerName: "Moisés Caicedo", teamName: "Ecuador", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 86 },
    { id: 3711, playerName: "Alan Franco", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3712, playerName: "Kendry Páez", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 82 },
    { id: 3713, playerName: "Jeremy Sarmiento", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 79 },
    { id: 3714, playerName: "José Cifuentes", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 79 },
    { id: 3715, playerName: "Carlos Gruezo", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 3716, playerName: "Gonzalo Plata", teamName: "Ecuador", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 82 },
    { id: 3717, playerName: "Leonardo Campana", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 79 },
    { id: 3718, playerName: "Kevin Rodríguez", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 78 },
    { id: 3719, playerName: "Allen Obando", teamName: "Ecuador", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 77 },
    // Curaçao
    { id: 3600, playerName: "Eloy Room", teamName: "Curaçao", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 81 },
    { id: 3601, playerName: "Trevor Doornbusch", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 75 },
    { id: 3602, playerName: "Cuco Martina", teamName: "Curaçao", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 77 },
    { id: 3603, playerName: "Ridgeciano Haps", teamName: "Curaçao", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 78 },
    { id: 3604, playerName: "Joshua Brenet", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Defender", overallRating: 76 },
    { id: 3605, playerName: "Sherel Floranus", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Defender", overallRating: 75 },
    { id: 3606, playerName: "Darryl Lachman", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Defender", overallRating: 74 },
    { id: 3607, playerName: "Jurien Gaari", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Defender", overallRating: 73 },
    { id: 3608, playerName: "Danzell Gravenberch", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Defender", overallRating: 72 },
    { id: 3609, playerName: "Leandro Bacuna", teamName: "Curaçao", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 80 },
    { id: 3610, playerName: "Juninho Bacuna", teamName: "Curaçao", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 79 },
    { id: 3611, playerName: "Vurnon Anita", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 76 },
    { id: 3612, playerName: "Godfried Roemeratoe", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 75 },
    { id: 3613, playerName: "Kevin Felida", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 74 },
    { id: 3614, playerName: "Roly Bonevacia", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 74 },
    { id: 3615, playerName: "Jürgen Locadia", teamName: "Curaçao", rarityLevel: "Uncommon", playerPosition: "Attacker", overallRating: 77 },
    { id: 3616, playerName: "Rangelo Janga", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 75 },
    { id: 3617, playerName: "Elson Hooi", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 74 },
    { id: 3618, playerName: "Gervane Kastaneer", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 73 },
    { id: 3619, playerName: "Kenji Gorré", teamName: "Curaçao", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 73 },
    // Ivory Coast
    { id: 3800, playerName: "Yahia Fofana", teamName: "Ivory Coast", rarityLevel: "Uncommon", playerPosition: "Goalkeeper", overallRating: 83 },
    { id: 3801, playerName: "Badra Ali Sangaré", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Goalkeeper", overallRating: 77 },
    { id: 3802, playerName: "Evan Ndicka", teamName: "Ivory Coast", rarityLevel: "Rare", playerPosition: "Defender", overallRating: 85 },
    { id: 3803, playerName: "Wilfried Singo", teamName: "Ivory Coast", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 84 },
    { id: 3804, playerName: "Odilon Kossounou", teamName: "Ivory Coast", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 83 },
    { id: 3805, playerName: "Ousmane Diomande", teamName: "Ivory Coast", rarityLevel: "Uncommon", playerPosition: "Defender", overallRating: 84 },
    { id: 3806, playerName: "Sinaly Diomandé", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Defender", overallRating: 80 },
    { id: 3807, playerName: "Ghislain Konan", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Defender", overallRating: 80 },
    { id: 3808, playerName: "Serge Aurier", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Defender", overallRating: 79 },
    { id: 3809, playerName: "Franck Kessié", teamName: "Ivory Coast", rarityLevel: "Rare", playerPosition: "Midfielder", overallRating: 85 },
    { id: 3810, playerName: "Ibrahim Sangaré", teamName: "Ivory Coast", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 3811, playerName: "Seko Fofana", teamName: "Ivory Coast", rarityLevel: "Uncommon", playerPosition: "Midfielder", overallRating: 83 },
    { id: 3812, playerName: "Hamed Junior Traorè", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 81 },
    { id: 3813, playerName: "Jean-Philippe Gbamin", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 79 },
    { id: 3814, playerName: "Lazare Amani", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Midfielder", overallRating: 78 },
    { id: 3815, playerName: "Sébastien Haller", teamName: "Ivory Coast", rarityLevel: "Rare", playerPosition: "Attacker", overallRating: 85 },
    { id: 3816, playerName: "Amad Diallo", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 82 },
    { id: 3817, playerName: "Simon Adingra", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 81 },
    { id: 3818, playerName: "Jérémie Boga", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 80 },
    { id: 3819, playerName: "Karim Konaté", teamName: "Ivory Coast", rarityLevel: "Common", playerPosition: "Attacker", overallRating: 79 },
];
